Fix: Traceback (most recent call last):   File "lr_finder.py", line 110, in <module>     plt.imsave('lr_finder.jpeg') TypeError: imsave() missing 1 required positional argument: 'arr'
Details:
    change method for saving result